### ISSUE TITLE
Game crashes with Minetest 0.4.16

### ISSUE THREAD

**Issue by Bonsaiheldin** [CasimirKaPazi/Voxelgarden#47]
Hello! I just downloaded your subgame, but i can't get it running, using the latest stable 0.4.16 on Ubuntu 64 bit. It crashes just before the ingame screen should appear, right after the loading completes.

I tried to remove all mods and add folder by folder until it crashes. I found out, that it works only when i remove **default** from the mods folder. But then, of course, the world is empty. But it must be something within that folder.

Here is my debug.txt: https://pastebin.com/9d2B2Zjg

**Comment by CasimirKaPazi** [comment]
The latest release compatible with Minetest 0.4.16 is this one: [Voxelgarden 0.4.16.2](https://github.com/CasimirKaPazi/Voxelgarden/releases/tag/0.4.16.2)

The current git version only works with the 0.5 development version of Minetest, because there are a lot of changes in 0.5 that break compatibility.

**Comment by Bonsaiheldin** [comment]
Oh right, i forgot to tell which version of Voxelgarden i tried. It's the 0.4.16.2 you mention. I can't get it running with the latest stable 0.4.16 of Minetest.

**Comment by CasimirKaPazi** [comment]
Ok that's stange. Normally there should be some error message of some sort. What also confuses me, is that in your menu you have no header and no mention of the subgame used in the upper left corner.

Do the other subgames work?
Does the header appear when you switch to another subgame and then back to VG?
Is there any more output when running minetest with "--verbose"?

**Comment by Bonsaiheldin** [comment]
The other subgames work, of course.

The header appears above the UI when i select a subgame below the UI instead of the world which was created with the subgame. I don't know if that's any different from the windows version of Minetest. By the way, i also tried the game with v6 and v7 mapgen, it crashed with both.

![](https://i.imgur.com/BND5art.png)

I ran the game with --verbose but it seems the error messages are just the same as without: https://pastebin.com/EZyARWz4

I now ran the game from the console and saw there some error which does not appear in the debug.txt file. It's in german, but maybe it helps somehow:

```
minetest: /build/minetest-wva50I/minetest-0.4.16/src/nodedef.cpp:691: void ContentFeatures::updateTextures(ITextureSource*, IShaderSource*, irr::scene::IMeshManipulator*, Client*, const TextureSettings&): Zusicherung »liquid_type == LIQUID_SOURCE« nicht erfüllt.
Abgebrochen (Speicherabzug geschrieben)
```

To me it looks like some kind of problem on my side, though i don't know what i could do. Also, i can play other subgames without any problem.

Sorry that i don't have any more infos. All i know is that the game runs when i remove the **default** folder from the mod folder of the subgame, which leads to an empty world and me falling forever. 😅

Maybe your subgame will work on later versions, either of Minetest or your subgame. I will keep an eye on it, it sounds promising! 😀

**Comment by CasimirKaPazi** [comment]
Thanks for the information. Can you please try replacing this definition in mods/default/nodes.lua line 466:

    -- Dummy node for valleys mapgen.
    minetest.register_node("default:river_water_source", {
	description = "River Water Dummy Node",
	drawtype = "liquid",
	tiles = {"default_water.png"},
	alpha = 160,
	paramtype = "light",
	walkable = false,
	pointable = false,
	diggable = false,
	buildable_to = true,
	drowning = false,
	drop = "",
	liquidtype = "source",
	liquid_alternative_flowing = "default:water_flowing",
	liquid_alternative_source = "default:water_source",
	liquid_renewable = false,
	groups = {water=3, liquid=3, not_in_creative_inventory=1},
    })

For now I can't think of anything else causing this error.

**Comment by Bonsaiheldin** [comment]
Wow. It finally seems to work with this piece of code. Very nice! 👍

I suggest to include this for everyone else, too.
