### ISSUE TITLE
Character floating in third person view

### ISSUE THREAD

**Issue by ghost** [CasimirKaPazi/Voxelgarden#51]
Minetest 0.4.16
Voxelgarden-master
Mapgen v6

First person view is ok, third person view shows the character "floating" one node above ground.

**Comment by CasimirKaPazi** [comment]
You need to use the [0.4.16 release](https://github.com/CasimirKaPazi/Voxelgarden/releases/tag/0.4.16.3). The master branch includes changes for Minetest 0.5. In 0.5 player height changed and is incompatible with earlier versions.
