### ISSUE TITLE
The .gitmodules file is missing

### ISSUE THREAD

**Issue by MrMetric** [CasimirKaPazi/Voxelgarden#54]
In commit 8ffc8b78a32a7d61d710f86160fb4fb6ae0f93fe, you added 2 submodules, but did not add the .gitmodules file, so those submodules can not be cloned:

    $ git submodule update --init
    fatal: No url found for submodule path 'mods/mobs' in .gitmodules

**Comment by CasimirKaPazi** [comment]
Thank you. I wasn't aware that I did that. Fixed in e6d436b.
