### ISSUE TITLE
Rats glow in the dark.

### ISSUE THREAD

**Issue by Wuzzy2** [CasimirKaPazi/Voxelgarden#60]
Rats glow in the dark.

Game version: 5.0.0
Minetest version: 5.0.1

**Comment by CasimirKaPazi** [comment]
Maybe a bug in minetest. I'll have to look into it.

**Comment by ElonSatoshi** [comment]
Well? Did you look into it?

**Comment by CasimirKaPazi** [comment]
No. Lately I spend almost no time with anything minetest related. Occasionally I will look for pull requests. I would be happy for others to take up the project in the same spirit.

**Comment by CasimirKaPazi** [comment]
^ Except for random bursts of activity.

I have seen it myself in the past, but now this doesn't seem to be an issue anymore. Does anyone still have this issue?

**Comment by Wuzzy2** [comment]
I haven't tested it in recent versions.

**Comment by CasimirKaPazi** [comment]
Never mind. Still a problem.

**Comment by CasimirKaPazi** [comment]
[#9021 in MT](https://github.com/minetest/minetest/pull/9021) might have fixed this. I wasn't able to reproduce now. In any case, it's and issue with the engine, not the game.
