### ISSUE TITLE
Falling nodes fall forever when falling on player

### ISSUE THREAD

**Issue by Wuzzy2** [CasimirKaPazi/Voxelgarden#61]
If a falling node like sand falls on a player, its position will repeatedly reset, causing the sand to be stuck in an infinite loop.

Steps to reproduce:
1. Have a sand column on top of stone.
2. Be under the stone.
3. Dig the stone

EXPECTED: Sand buries you.
ACTUAL: Sand resets position all the time.

**Comment by CasimirKaPazi** [comment]
It's funny. Now that the changes I did in falling.lua where also reinvented for MTG, I just had to remove my old code and retain the same functionality. The only thing missing is a delay to spawning nodes. See 75add6a.
