### ISSUE TITLE
Several console warnings

### ISSUE THREAD

**Issue by Wuzzy2** [CasimirKaPazi/Voxelgarden#70]
These warnings appear on startup:

```
WARNING[Main]: Not registering alias, item with same name is already defined: default:rail -> carts:rail
WARNING[Main]: Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
WARNING[Main]: Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
WARNING[Main]: Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
WARNING[Main]: Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
WARNING[Server]: Undeclared global variable "creative" accessed at /home/wuzzy/.minetest/games/voxelgarden/mods/map/init.lua:22
```

There are many other warnings, usually about undeclared globals, when you continue playing the game.

**Comment by CasimirKaPazi** [comment]
I think most warnings have been fixed. Only the "creative" in the maps mod remains. This is because I use an old variant of creative mode and the map mod assumes the one in minetest_game. But i also don't want to change either just because of one warning.
