### ISSUE TITLE
Many recipes missing in craftguide

### ISSUE THREAD

**Issue by Wuzzy2** [CasimirKaPazi/Voxelgarden#71]
In the craftguide, many recipes are missing. For example, none of the tool recipes are visible.
But also the recipe for sticks is incomplete. You only see the recipe "3 dry shrub" but not "3 leaves".

2d9d2f75824e9afe216254d303523a9cc545d56c

**Comment by CasimirKaPazi** [comment]
a6d8b7ca3f01209d4fed3c4489d0709dda270396
