### ISSUE TITLE
Any created world made of stone only

### ISSUE THREAD

**Issue by Ygarr** [CasimirKaPazi/Voxelgarden#78]
The game creates only worlds with  landscape looks like on screenshot. 
No other biomes. Absolutely lifeless
![screenshot_20211016_024502](https://user-images.githubusercontent.com/14309871/137565147-292e821c-2c03-4c35-af0a-011fff5cf905.png)
.

**Comment by CasimirKaPazi** [comment]
What version of Minetest and Voxelgarden are you useing? Which mapgen? For me it works fine.

**Comment by Skamiz** [comment]
Most likely OP made a world in another game which disables biomes earlier and now they are disabled for all games.
Can be checked by looking for 'mg_flags' in map_meta.txt of the world.

**Comment by CasimirKaPazi** [comment]
That's very likely the cause.
